//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.23 at 02:07:45 PM EST 
//


package gov.nyc.doitt.pressreleases.jaxb.pressrelease;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MediaContactType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MediaContactType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="contact_person" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="agency_text_link" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="agency_link_url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phone" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MediaContactType", propOrder = {
    "contactPerson",
    "agencyTextLink",
    "agencyLinkUrl",
    "phone"
})
public class MediaContactType {

    @XmlElement(name = "contact_person", required = true)
    protected String contactPerson;
    @XmlElement(name = "agency_text_link", required = true)
    protected String agencyTextLink;
    @XmlElement(name = "agency_link_url", required = true)
    protected String agencyLinkUrl;
    protected int phone;

    /**
     * Gets the value of the contactPerson property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactPerson() {
        return contactPerson;
    }

    /**
     * Sets the value of the contactPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactPerson(String value) {
        this.contactPerson = value;
    }

    /**
     * Gets the value of the agencyTextLink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgencyTextLink() {
        return agencyTextLink;
    }

    /**
     * Sets the value of the agencyTextLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgencyTextLink(String value) {
        this.agencyTextLink = value;
    }

    /**
     * Gets the value of the agencyLinkUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgencyLinkUrl() {
        return agencyLinkUrl;
    }

    /**
     * Sets the value of the agencyLinkUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgencyLinkUrl(String value) {
        this.agencyLinkUrl = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     */
    public int getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     */
    public void setPhone(int value) {
        this.phone = value;
    }

}
