//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.23 at 02:07:45 PM EST 
//


package gov.nyc.doitt.pressreleases.jaxb.pressrelease;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.nyc.doitt.pressreleases.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PressRelease_QNAME = new QName("", "press_release");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.nyc.doitt.pressreleases.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PressReleaseType }
     * 
     */
    public PressReleaseType createPressReleaseType() {
        return new PressReleaseType();
    }

    /**
     * Create an instance of {@link PublicContactType }
     * 
     */
    public PublicContactType createPublicContactType() {
        return new PublicContactType();
    }

    /**
     * Create an instance of {@link RelatedSoundContentType }
     * 
     */
    public RelatedSoundContentType createRelatedSoundContentType() {
        return new RelatedSoundContentType();
    }

    /**
     * Create an instance of {@link LinkType }
     * 
     */
    public LinkType createLinkType() {
        return new LinkType();
    }

    /**
     * Create an instance of {@link MediaContactType }
     * 
     */
    public MediaContactType createMediaContactType() {
        return new MediaContactType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PressReleaseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "press_release")
    public JAXBElement<PressReleaseType> createPressRelease(PressReleaseType value) {
        return new JAXBElement<PressReleaseType>(_PressRelease_QNAME, PressReleaseType.class, null, value);
    }

}
