//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.23 at 02:07:45 PM EST 
//


package gov.nyc.doitt.pressreleases.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for press_releaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="press_releaseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="info_type" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="press_release_guid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="pr_number" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="official_title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="permalink_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="brief_pr_title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="paragraph" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="categories" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="photo_option" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="MediaContact" type="{}MediaContactType"/>
 *         &lt;element name="PublicContact" type="{}PublicContactType"/>
 *         &lt;element name="Link" type="{}LinkType"/>
 *         &lt;element name="side_bar_conent" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="RelatedSound_Content" type="{}RelatedSound_ContentType"/>
 *         &lt;element name="RelatedVideo_Content" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="content_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Mobile_Options" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Other" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "press_releaseType", propOrder = {
    "infoType",
    "pressReleaseGuid",
    "language",
    "date",
    "prNumber",
    "officialTitle",
    "permalinkName",
    "briefPrTitle",
    "paragraph",
    "categories",
    "photoOption",
    "mediaContact",
    "publicContact",
    "link",
    "sideBarConent",
    "relatedSoundContent",
    "relatedVideoContent",
    "contentType",
    "mobileOptions",
    "other"
})
public class PressReleaseType {

    @XmlElement(name = "info_type")
    protected int infoType;
    @XmlElement(name = "press_release_guid", required = true)
    protected String pressReleaseGuid;
    @XmlElement(required = true)
    protected String language;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar date;
    @XmlElement(name = "pr_number", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar prNumber;
    @XmlElement(name = "official_title", required = true)
    protected String officialTitle;
    @XmlElement(name = "permalink_name", required = true)
    protected String permalinkName;
    @XmlElement(name = "brief_pr_title", required = true)
    protected String briefPrTitle;
    @XmlElement(required = true)
    protected String paragraph;
    @XmlElement(required = true)
    protected String categories;
    @XmlElement(name = "photo_option")
    protected int photoOption;
    @XmlElement(name = "MediaContact", required = true)
    protected MediaContactType mediaContact;
    @XmlElement(name = "PublicContact", required = true)
    protected PublicContactType publicContact;
    @XmlElement(name = "Link", required = true)
    protected LinkType link;
    @XmlElement(name = "side_bar_conent")
    protected int sideBarConent;
    @XmlElement(name = "RelatedSound_Content", required = true)
    protected RelatedSoundContentType relatedSoundContent;
    @XmlElement(name = "RelatedVideo_Content", required = true)
    protected String relatedVideoContent;
    @XmlElement(name = "content_type", required = true)
    protected String contentType;
    @XmlElement(name = "Mobile_Options", required = true)
    protected String mobileOptions;
    @XmlElement(name = "Other", required = true)
    protected String other;

    /**
     * Gets the value of the infoType property.
     * 
     */
    public int getInfoType() {
        return infoType;
    }

    /**
     * Sets the value of the infoType property.
     * 
     */
    public void setInfoType(int value) {
        this.infoType = value;
    }

    /**
     * Gets the value of the pressReleaseGuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPressReleaseGuid() {
        return pressReleaseGuid;
    }

    /**
     * Sets the value of the pressReleaseGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPressReleaseGuid(String value) {
        this.pressReleaseGuid = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the prNumber property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPrNumber() {
        return prNumber;
    }

    /**
     * Sets the value of the prNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPrNumber(XMLGregorianCalendar value) {
        this.prNumber = value;
    }

    /**
     * Gets the value of the officialTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfficialTitle() {
        return officialTitle;
    }

    /**
     * Sets the value of the officialTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfficialTitle(String value) {
        this.officialTitle = value;
    }

    /**
     * Gets the value of the permalinkName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPermalinkName() {
        return permalinkName;
    }

    /**
     * Sets the value of the permalinkName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPermalinkName(String value) {
        this.permalinkName = value;
    }

    /**
     * Gets the value of the briefPrTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBriefPrTitle() {
        return briefPrTitle;
    }

    /**
     * Sets the value of the briefPrTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBriefPrTitle(String value) {
        this.briefPrTitle = value;
    }

    /**
     * Gets the value of the paragraph property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParagraph() {
        return paragraph;
    }

    /**
     * Sets the value of the paragraph property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParagraph(String value) {
        this.paragraph = value;
    }

    /**
     * Gets the value of the categories property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategories() {
        return categories;
    }

    /**
     * Sets the value of the categories property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategories(String value) {
        this.categories = value;
    }

    /**
     * Gets the value of the photoOption property.
     * 
     */
    public int getPhotoOption() {
        return photoOption;
    }

    /**
     * Sets the value of the photoOption property.
     * 
     */
    public void setPhotoOption(int value) {
        this.photoOption = value;
    }

    /**
     * Gets the value of the mediaContact property.
     * 
     * @return
     *     possible object is
     *     {@link MediaContactType }
     *     
     */
    public MediaContactType getMediaContact() {
        return mediaContact;
    }

    /**
     * Sets the value of the mediaContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediaContactType }
     *     
     */
    public void setMediaContact(MediaContactType value) {
        this.mediaContact = value;
    }

    /**
     * Gets the value of the publicContact property.
     * 
     * @return
     *     possible object is
     *     {@link PublicContactType }
     *     
     */
    public PublicContactType getPublicContact() {
        return publicContact;
    }

    /**
     * Sets the value of the publicContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicContactType }
     *     
     */
    public void setPublicContact(PublicContactType value) {
        this.publicContact = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link LinkType }
     *     
     */
    public LinkType getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkType }
     *     
     */
    public void setLink(LinkType value) {
        this.link = value;
    }

    /**
     * Gets the value of the sideBarConent property.
     * 
     */
    public int getSideBarConent() {
        return sideBarConent;
    }

    /**
     * Sets the value of the sideBarConent property.
     * 
     */
    public void setSideBarConent(int value) {
        this.sideBarConent = value;
    }

    /**
     * Gets the value of the relatedSoundContent property.
     * 
     * @return
     *     possible object is
     *     {@link RelatedSoundContentType }
     *     
     */
    public RelatedSoundContentType getRelatedSoundContent() {
        return relatedSoundContent;
    }

    /**
     * Sets the value of the relatedSoundContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelatedSoundContentType }
     *     
     */
    public void setRelatedSoundContent(RelatedSoundContentType value) {
        this.relatedSoundContent = value;
    }

    /**
     * Gets the value of the relatedVideoContent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatedVideoContent() {
        return relatedVideoContent;
    }

    /**
     * Sets the value of the relatedVideoContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatedVideoContent(String value) {
        this.relatedVideoContent = value;
    }

    /**
     * Gets the value of the contentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * Sets the value of the contentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentType(String value) {
        this.contentType = value;
    }

    /**
     * Gets the value of the mobileOptions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobileOptions() {
        return mobileOptions;
    }

    /**
     * Sets the value of the mobileOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobileOptions(String value) {
        this.mobileOptions = value;
    }

    /**
     * Gets the value of the other property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOther() {
        return other;
    }

    /**
     * Sets the value of the other property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOther(String value) {
        this.other = value;
    }

}
