//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.23 at 02:07:45 PM EST 
//


package gov.nyc.doitt.pressreleases.jaxb.pressrelease;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RelatedSound_ContentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RelatedSound_ContentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="related_sound_source" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelatedSound_ContentType", propOrder = {
    "relatedSoundSource"
})
public class RelatedSoundContentType {

    @XmlElement(name = "related_sound_source")
    protected int relatedSoundSource;

    /**
     * Gets the value of the relatedSoundSource property.
     * 
     */
    public int getRelatedSoundSource() {
        return relatedSoundSource;
    }

    /**
     * Sets the value of the relatedSoundSource property.
     * 
     */
    public void setRelatedSoundSource(int value) {
        this.relatedSoundSource = value;
    }

}
