//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.23 at 02:43:30 PM EST 
//


package gov.nyc.doitt.pressreleases.jaxb.searchresults;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.nyc.doitt.pressreleases.jaxb.searchresults package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Results_QNAME = new QName("", "results");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.nyc.doitt.pressreleases.jaxb.searchresults
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ResultsType }
     * 
     */
    public ResultsType createResultsType() {
        return new ResultsType();
    }

    /**
     * Create an instance of {@link AssetsType }
     * 
     */
    public AssetsType createAssetsType() {
        return new AssetsType();
    }

    /**
     * Create an instance of {@link DocumentType }
     * 
     */
    public DocumentType createDocumentType() {
        return new DocumentType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResultsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "results")
    public JAXBElement<ResultsType> createResults(ResultsType value) {
        return new JAXBElement<ResultsType>(_Results_QNAME, ResultsType.class, null, value);
    }

}
