CREATE TABLE ITEMS(
	ID NUMBER(10) PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(1000),
    IMAGE_URI VARCHAR2(200)
);

CREATE TABLE CUSTOMERS(
	ID NUMBER(10) PRIMARY KEY,
    GIVEN_NAME VARCHAR2(100) NOT NULL,
    FAMILY_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL
);

CREATE TABLE ORDERS(
	ID NUMBER(10) PRIMARY KEY,
    CREATION_DATE TIMESTAMP(0) DEFAULT SYSTIMESTAMP NOT NULL ,
    LAST_UPDATE TIMESTAMP(0) DEFAULT SYSTIMESTAMP NOT NULL ,
    CUST_ID NUMBER(10),
    STATUS VARCHAR2(10) DEFAULT 'OPEN' NOT NULL,
    FOREIGN KEY(CUST_ID) REFERENCES CUSTOMERS(ID)
);

CREATE TABLE ORDER_ITEMS(
	ORDER_ID NUMBER(10),
    ITEM_ID NUMBER(10),
    QUANITY NUMBER(10),
    FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ID),
    FOREIGN KEY(ITEM_ID) REFERENCES ITEMS(ID),
    PRIMARY KEY(ORDER_ID, ITEM_ID)
    
);